algoritmo "Operadores"
// Função :
// Autor :
// Data : 5/2/2011
// Seção de Declarações 
var
Resultado1, Resultado2 : real
Resultado3 : logico
texto : caracter

inicio
texto <- "Exemplo de Operadores"
Escreval (maiusc (texto))
Resultado1 <- 9 mod 2
Resultado2 <- 8^2 + 10 * 2
Resultado3 <- 15 <> 2
Escreval ("9 mod 2 =", resultado1)
Escreval ("8^2 + 10 * 2=", resultado2)
Escreval ("15 <> 2 =",resultado3)
// Seção de Comandos 
fimalgoritmo
